name: Cross-Platform Build and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Upload Binaries
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: bash

      - name: Build Binary
        run: |
          pyinstaller --onefile --name sdrive sdrive/main.py
        shell: bash

      - name: Rename and Organize Binary
        run: |
          mkdir -p dist/${{ matrix.platform }}_${{ matrix.arch }}
          mv dist/sdrive dist/${{ matrix.platform }}_${{ matrix.arch }}/sdrive${{ matrix.platform == 'windows-latest' && '.exe' || '' }}
        shell: bash

      - name: Create Zip File (Linux/macOS)
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          cd dist
          zip -r ${{ matrix.platform }}_${{ matrix.arch }}.zip ${{ matrix.platform }}_${{ matrix.arch }}

      - name: Create Zip File (Windows)
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          powershell Compress-Archive -Path dist\${{ matrix.platform }}_${{ matrix.arch }}\* -DestinationPath dist\${{ matrix.platform }}_${{ matrix.arch }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}_${{ matrix.arch }}
          path: dist/${{ matrix.platform }}_${{ matrix.arch }}.zip
