name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]  # Use a single Python version
        architecture: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    # Build the executable with PyInstaller
    - name: Build executable
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          python -m PyInstaller --onefile `
            --name sdrive_${{ matrix.os }}_${{ matrix.architecture }} `
            sdrive/main.py
        else
          python -m PyInstaller --onefile \
            --name sdrive_${{ matrix.os }}_${{ matrix.architecture }} \
            sdrive/main.py

    # Upload the artifact
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: sdrive-${{ matrix.os }}-${{ matrix.architecture }}
        path: dist/
