name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64] # Build for different architectures
    runs-on: ${{ matrix.os }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    # Debug OS and Architecture
    - name: Debug OS and Architecture
      run: |
        echo "Operating System: ${{ matrix.os }}"
        echo "Architecture: ${{ matrix.architecture }}"

    # Build the executable with PyInstaller
    - name: Build executable
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          python -m PyInstaller --onefile `
            --name sdrive_${{ matrix.os }}_${{ matrix.architecture }} `
            sdrive/main.py
        else
          python -m PyInstaller --onefile \
            --name sdrive_${{ matrix.os }}_${{ matrix.architecture }} \
            sdrive/main.py
        fi

    # Upload the binary
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: sdrive-${{ matrix.os }}-${{ matrix.architecture }}
        path: dist/
